language: node_js

node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-9-jdk
  - export SAML_VALIDATOR=javac

script:
  - npm test

branches:
  only:
  - master
  - /^.*-alpha$/
  - /^.*-beta$/

after_success: npm run coverage