language: node_js

node_js:
  - "6"
  - "8"
  - "10"

env:
  - INSTALL_JDK=1
  - INSTALL_JDK=0

before_install:
  - if [[ "$INSTALL_JDK" == "1" ]] ; then make install_jdk ; fi

script:
  - npm test

branches:
  only:
  - master
  - /^.*-alpha$/
  - /^.*-rc.*$/

after_success: npm run coverage